const IMAGES = {
  logo: require('../assets/images/logo.png'),
  filter: require('../assets/images/filter.png'),
  profileImg: require('../assets/images/profile_placeholder.png'),
  CardsFocused: require('../assets/images/Cards.png'),
  BatchCardsFocued: require('../assets/images/BatchCards.png'),
  EditNFCFocused: require('../assets/images/nfcFocued.png'),
  Cards: require('../assets/images/cardN.png'),
  BatchCards: require('../assets/images/BatchCardsN.png'),
  EditNFC: require('../assets/images/nfc.png'),
  readNfc: require('../assets/images/cardRead.png'),
  whatsApp: require('../assets/images/whatsApp.png'),
  insta: require('../assets/images/insta.png'),
  twitter: require('../assets/images/twitter.png'),
  linkedin: require('../assets/images/linkedin.png'),
  facebook: require('../assets/images/facebook.png'),
  threads: require('../assets/images/threads.png'),
  phone: require('../assets/images/phone.png'),
  snapChat: require('../assets/images/snapChat.png'),
  spotify: require('../assets/images/spotify.png'),
  telegram: require('../assets/images/telegram.png'),
  tiktok: require('../assets/images/tiktok.png'),
  website: require('../assets/images/website.png'),
  gmail: require('../assets/images/gmail.png'),
  email: require('../assets/images/email.png'),
};
export {IMAGES};
